### ISSUE TITLE
Pushable bombs

### ISSUE THREAD

**Issue by ObaniGemini** [akien-mga/dynadungeons#11]
Could it be possible to add a bind to push bombs? Bombs could be pushed by all players and wouldn't stop rolling until they hurt an entity (bomb, player, walls, breakable box and trees)

**Comment by akien-mga** [comment]
Support for kicking bombs was added in b5abfb7b. What missing to close this issue is to make it a skill that you obtain through a collectible, as it the Bombermans from SNES that I use as a reference :)
