### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by akien-mga** [akien-mga/dynadungeons#12]
The game needs some sound effects :) I'll have a first look at what I can find on OGA or similar resources for openly licensed sound effects.

First list (to be extended):
- [x] Collectible pickup sound
- [x] Bomb drop
- [x] Bomb push
- [x] Bomb explosion
- [x] Player death
- [x] Player respawn

**Comment by ObaniGemini** [comment]
Let's go !

**Comment by akien-mga** [comment]
The first set is already quite interesting IMO, even if it's of course not perfect. Could you make a sound for collectible pickup, and one for dropping bombs (something simple, maybe just a muffled sound) so that we get the big picture?

Then we can work on fine-tuning, seeing which sounds are good, which don't really fit, etc.

I'll add an option to adjust the music volume and SFX volume separately.

**Comment by ghost** [comment]
This is pretty fun to play with, even just for prototyping sounds: http://www.bfxr.net/

You also get full rights to any sounds created with it.

**Comment by ghost** [comment]
One for pickup? http://soundbible.com/2068-Woosh.html

**Comment by ghost** [comment]
And maybe this for bomb drop? http://soundbible.com/2044-Tick.html

edit: Or this? :P http://soundbible.com/1949-Pew-Pew.html

**Comment by akien-mga** [comment]
> One for pickup? http://soundbible.com/2068-Woosh.html

Sounds pretty good, I'll upload it tonight.

> And maybe this for bomb drop? http://soundbible.com/2044-Tick.html

This one is not perfect, but could start as a placeholder. I can maybe try to play with the pitch to make it sounds more "heavy".

> Or this? :P http://soundbible.com/1949-Pew-Pew.html

Lool

**Comment by akien-mga** [comment]
There are some pretty good sounds on soundbible.

I found this for bomb drop: http://soundbible.com/1120-Bounce.html

Also some interesting bomb explosion sounds:
http://soundbible.com/107-Bomb-Explosion-1.html
http://soundbible.com/1467-Grenade-Explosion.html
