### ISSUE TITLE
Scene structure

### ISSUE THREAD

**Issue by ghost** [akien-mga/dynadungeons#18]
Hi @akien-mga, I was looking for a project to gain some programming experience on and was hoping to jump in on this if that's alright :)

How would you feel about arranging the layout of the scenes to be more like [this](https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-9/11219534_10207764230531499_1178689360557705457_n.jpg?oh=0847afa6e6a087742365bbdcae83aa83&oe=5645BFFB&__gda__=1451307757_ac4922c9aa486a91be31cab3df60d975)? 

There could be a single 'global' scene (like 'World' in the image) that contains instances of the other scenes (UI/Player/Current Level/Main Menu). I think this would make it easier to work in re-usable scenes like a pause menu or a gameover screen.

Let me know what you think! If you're happy with doing that I can make some changes and send you a PR.

**Comment by akien-mga** [comment]
Hi @deliciousfudge and welcome :)
Yeah I'd be very glad if you want to help with DynaDungeons; you'll see that I'm a beginner programmer too, so don't hesitate to question my design choices, some of them might definitely be poor.

Regarding the scenes structure, I agree that it needs to be rearranged. The main reason being to have support for different levels, currently everything is organised via the level scene, so it can't be changed easily (though arguably the real "level" part of this scene is only the map manager, so the level scene could probably be renamed and converted to a "world" scene, if the tilemaps were split into another customisable scene.

If you already have something more specific in mind (maybe also taking into account that we'll soon need a UI, cf. #15), I'd be glad to review a PR :)

Regarding commit guidelines, I more or less try to follow https://github.com/agis-/git-style-guide

**Comment by ghost** [comment]
Awesome!

Your idea sounds good. I'll have a read through that style guide and get something through to you :)

**Comment by akien-mga** [comment]
Fixed by #20.
