### ISSUE TITLE
Some ideas of gameplay features for DynaDungeons

### ISSUE THREAD

**Issue by ObaniGemini** [akien-mga/dynadungeons#2]
The first idea would be that player have 2 or 3 lifes. I can make the textures for it. They would lose a life when got kill (_Edit:_ now in #3).

The second idea would be that power-ups are as undestructible walls : You can take them, but fire can't go threw them (_Edit:_ now in #4).

The third idea would be to add bonuse and maluses (_Edit:_ now in #5). 
Bonuses : 
- Nyan Cat : Your avatar becames a nyan cat that is invicible to al kind of deathly item
- Speed Up : Your avatar walks faster
- Controlled Bombs : you can now control when your bombs explode

Maluses : 
- Skull head : Kills instantely. With the second idea, it would make a static killing bloc that cannot be destroyed, except by Nyan Cat.
- Slow down : Your avatar walks slower.
- Confusion : Keys inverted

The fourth idea would be to add destructible blocs spawning at some random places on grass. If they spawn on you, you die. (Idea taken from Bomberman64 versus mode)

**Comment by akien-mga** [comment]
> The first idea would be that player have 2 or 3 lifes. I can make the textures for it. They would lose a life when got kill.

Yes that could be interesting. I think I'll make many things configurable through the yet-to-code-and-design GUI, so I'll make sure that one can select how many lives each player should have (it will also be useful if we make a singleplayer/RPG mode, where we don't want to be able to lose the game so easily).

> The second idea would be that power-ups are as undestructible walls : You can take them, but fire can't go threw them.

Yep, that's on my mental todo-list. It's how it behaves in Bomberman. The power-ups should actually get destroyed by bombs too, i.e. behave as objects of the "Destructible" tilemap.

> The third idea would be to add bonuse and maluses.

Good idea too, that's also on my todo-list :)

> The fourth idea would be to add destructible blocs spawning at some random places on grass. If they spawn on you, you die. (Idea taken from Bomberman64 versus mode)

Why not, but I guess there should be some visual feedback first that tells that a block will appear soon (like a growing shadow?).

I'll open tickets for the first 3 ideas, and we can probably continue to use this thread to throw in ideas, and split them into their own tickets once they are validated :)
_Edit:_ Done :)

**Comment by akien-mga** [comment]
Closing as this thread was superseded by three other issues.
