### ISSUE TITLE
.play() takes an argument in current development version of godot

### ISSUE THREAD

**Issue by firefly2442** [akien-mga/dynadungeons#28]
https://github.com/akien-mga/dynadungeons/blob/master/scripts/level.gd#L79

.play() takes an argument now in the development version (master branch) of godot.

**Comment by akien-mga** [comment]
Indeed, though looking at the API changes it seems to be bogus on Godot's side, I'll open a ticket upstream.

**Comment by akien-mga** [comment]
Upstream bug report: https://github.com/okamstudio/godot/issues/2492

**Comment by akien-mga** [comment]
Should be fixed in current Godot master.
