### ISSUE TITLE
Issues with tileset.tres

### ISSUE THREAD

**Issue by ghost** [akien-mga/dynadungeons#31]
Hope you're well @akien-mga :)

I cloned straight from the repo and it looks like there is an issue with the tileset.tres file (doesn't like the Rect2 identifier for some reason), which is rippling through to the level.tscn and world.tcsn files and disrupting them from loading.

![screenshot from 2015-12-26 21 22 41](https://cloud.githubusercontent.com/assets/5356866/12005664/da3c68a4-ac16-11e5-8287-fd62c7e64e2f.png)

Not quite sure what the correct identifier is, but I've only had a brief look for it. Any ideas?

**Comment by akien-mga** [comment]
I think you need a more recent snapshot of godot, this issue was fixed a couple weeks ago (about the same time when I added tileset.tres).

**Comment by ghost** [comment]
That seemed to solve things. Thanks!
