### ISSUE TITLE
Apply the Kobuge style guide

### ISSUE THREAD

**Issue by akien-mga** [akien-mga/dynadungeons#34]
As I co-authored it, I propose to use the Kobuge style guide for this game, and I'll thus do the needed changes in the scripts and scenes: https://github.com/KOBUGE-Games/resources/blob/master/STYLE-GUIDE.md

The only exception I'll take is that I'll keep nodes named with "PascalCase" instead of "snake_case". Matter of taste mostly, and also to prevent having to rename _all_ nodes as I was already using PascalCase as a convention :)

**Comment by akien-mga** [comment]
More or less fixed with 8ef311d and the two following commits. It's arguably quite arbitrary and maybe not worth creating those huge diffs, but it had the merit to get me looking at the code, which is not negligible lately :D

**Comment by ObaniGemini** [comment]
That was quite fast !
