### ISSUE TITLE
Powerups should be destroyed by bombs and limit their range

### ISSUE THREAD

**Issue by akien-mga** [akien-mga/dynadungeons#4]
Quoting #2:

> > The second idea would be that power-ups are as undestructible walls : You can take them, but fire can't go threw them.
> 
> Yep, that's on my mental todo-list. It's how it behaves in Bomberman. The power-ups should actually get destroyed by bombs too, i.e. behave as objects of the "Destructible" tilemap.

**Comment by ObaniGemini** [comment]
I though about not destructing power-ups.
As it, when you're locked by a mallus, you can't do something other than take it

**Comment by akien-mga** [comment]
> I though about not destructing power-ups.
> As it, when you're locked by a mallus, you can't do something other than take it

Usually, if you are blocked by a negative powerups, you will not have enough movement space to be able to destroy it with a bomb with blowing yourself up ;-) So IMO we should make it possible to destroy negative powerups as in the original bomberman, apart from some special powerups that should only be teleported somewhere else when destroyed.

**Comment by ObaniGemini** [comment]
Yes, ok :)
