### ISSUE TITLE
Re-compiling the entire engine to change the executable icon -> NOT A PRIORITY! <-- LOL!

### ISSUE THREAD

**Issue by ContinueToBuryHeadInSand** [akien-mga/dynadungeons#61]
### JUST IN

![](https://i.imgur.com/dlWPgII.jpg)

---

(Since everyone keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.

He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable >_<

**Comment by ContinueToBuryHeadInSand** [comment]
@akien-mga Forgot to lock down your repos, mate

**Comment by ContinueToBuryHeadInSand** [comment]
![](https://media.giphy.com/media/14ceV8wMLIGO6Q/giphy.gif)

**Comment by akien-mga** [comment]
Nah, I couldn't care less about your spam here :)

**Comment by ContinueToBuryHeadInSand** [comment]
Well, I originally posted this topic several days ago  just once, and it was closed. Not only closed, but labeled "archive". I just wanted one discussion thread to be opened to discuss the stuff. Now, all that energy is built up and spam commenced. Apologizes in advance, but there were really no other places to post it. Facebook community would have pounced on me as usual, downvoted on reddit, etc.

**Comment by akien-mga** [comment]
It was closed because it's not a GitHub issue, it has nothing to do with a bug or feature of Godot Engine.

If you have a personal gripe with Juan and I, we can discuss it by email just fine. Your defamation campaign is not a "discussion thread", it's your own sided view of how we have wronged you, elegantly omitting all the context to try to sway people your side. That's dishonest, and you know it. It's also a complete overreaction.

If you just want to talk, write to us and we'll talk. But spamming doesn't solve anything, it just makes us less patient with you and less willing to be friendly. Your call.

**Comment by ContinueToBuryHeadInSand** [comment]
> It was closed because it's not a GitHub issue, it has nothing to do with a bug or feature of Godot Engine.

**Comment by ContinueToBuryHeadInSand** [comment]
> It was closed because it's not a GitHub issue, it has nothing to do with a bug or feature of Godot Engine.

Just like how Juan's "BETA" thread is still open, when it's not an issue? Why is there a double standard against me?  

Sick of it.

**Comment by ContinueToBuryHeadInSand** [comment]
If Godot had an actual forum where people could discuss this stuff, it would have never been an issue. It would just be one dumb drama thread. And I'd probably look like a retard while everyone agreed with Juan (which is what it looks like now), but just saying.

**Comment by akien-mga** [comment]
> Just like how Juan's "BETA" thread is still open, when it's not an issue? 

Well now it's closed. And it was a thread that had to do with Godot Engine (the program). Your war against Juan and I has nothing to do with Godot Engine, it has to do with you and us.

> Why is there a double standard against me?

Because you're harassing us? Is that hard to understand why there might be a double standard, and why we get you blocked and your accounts deleted as soon as GitHub staff is awake? Come on, open your eyes a bit and try to understand.

If you were **constructive** from the start (or started being constructive now, stopping your spam, stopping to hide against vendetta nicknames, and providing relevant comments to issues as you've done it sometimes in the past), you would be listened to, just like all the hundreds of other constructive bug reporters on the Godot repo.

**Comment by akien-mga** [comment]
> If Godot had an actual forum where people could discuss this stuff, it would have never been an issue. It would just be one dumb drama thread. And I'd probably look like a retard while everyone agreed with Juan (which is what it looks like now), but just saying.

Well that's what Reddit has been. Things have been discussed, it has turned into a drama thread. Most redditers were even on your side, so you could have left it at that.

**Comment by akien-mga** [comment]
At any rate, I'll ask a last time: please stop your spam. It's mildly annoying, a waste of time for everyone, and it takes our time away from working on Godot, which sucks for everyone, you included.

If you want to discuss further/still feel like we wronged you, we can discuss it privately as I mentioned. You know that, contrarily to what your OP states, Juan and I are both very patient and forthcoming, and it takes *a lot* to make us be impolite (which did happen in the reddit thread, but we've both apologized already and we've been over that countless times). This spamming campaign achieves nothing, but reasonable discussion (which doesn't have to be on a spam thread like this one) could do wonders.

**Comment by ContinueToBuryHeadInSand** [comment]
> Godot Engine, it has to do with you and us.

If a redditor is giving feedback and is being treated like that, it has everything to do with the community because you are the leaders listening to them. And represent the community. Users that give feedback should not have to worry, that they might be given that treatment. That's all I'm trying to convey

I know you and Juan are cordial. However, just because you are cordial doesn't give you guys the right to snap and then just "apologize" about it. There has to be change

**Comment by ContinueToBuryHeadInSand** [comment]
> It's mildly annoying, a waste of time for everyone,

Kind of like giving honest feedback about the engine and telling that person they are a coward in doing so. That must make them feel like they are not wasting their time at all! /s

**Comment by ContinueToBuryHeadInSand** [comment]
Also, I wouldn't recommend replying to me too much. Github will nuke this account within minutes ^^

**Comment by ContinueToBuryHeadInSand** [comment]
> but reasonable discussion (which doesn't have to be on a spam thread like this one) could do wonders.

LMAO and where the fuck would you recommend that be posted at?

**Comment by ContinueToBuryHeadInSand** [comment]
Closed, kicking to 4.1
