### ISSUE TITLE
Godot 3 Support

### ISSUE THREAD

**Issue by notzoom** [akien-mga/dynadungeons#62]
Hello - I have seen in one of your commits that you made efforts to ensure Godot 3 compatibility but upon trying this, it does not work. An issue with the preload scenes. If you could look into making it compatible I would be really thankful since it's a nice little game !

**Comment by akien-mga** [comment]
I just made the .fnt files compatible with the Godot format, but everything else still requires Godot 2.

Porting to Godot 3 is not trivial, there's some badly designed code that needs to be rewritten completely as it depends on a feature which was removed from Godot 3.

I've done some porting work locally (mostly to test and improve the Godot 2 to 3 converter), but not finished yet.

**Comment by akien-mga** [comment]
I merged a Godot 3.x port back in 2021 with #63.
