### ISSUE TITLE
Remi, you are not an engineer

### ISSUE THREAD

**Issue by ghost** [akien-mga/dynadungeons#64]
@akien-mga  and godot devs : Stop calling yourselves Engineers. You are not engineers, not event close, and never will be. You all don't have a clue as to what engineering means or entails. Sitting behind a keyboard and writing code has absolutely NOTHING to do with engineering. Software developers are not engineers, they are big liars when they make such stupid claims. Engineering is about designing and building physical entities, like buildings, turbines and machinery. So stop the false lies and offensive accusations.

**Comment by akien-mga** [comment]
Tough luck spammer, I have an MSc in Energy Engineering.
