### ISSUE TITLE
The game does not work with current Godot version 4.3

### ISSUE THREAD

**Issue by rzejek** [akien-mga/dynadungeons#68]
The project does not import to current Godot version 4.3.
The problem occur while importing font file. Import stops at 1%.

The output from console is:
Unicode parsing error, some characters were replaced with � (U+FFFD): Missing 1 UTF-8 continuation byte(s)

I'd like to run the game on linux system with the current Godot version.

**Comment by Babrakov** [comment]
Unfortunately there are many problems besides just importing fonts. I was able to import the project into Godot 4.3. But only the start menu works properly, and that after some corrections.
So the best and easiest way to run this project under Linux is to download Godot 3.x https://godotengine.org/download/3.x/linux/
And open the project there.

**Comment by akien-mga** [comment]
Yes this is a Godot 3.x project, it doesn't aim to support Godot 4 at this stage.

I might port it one day but it's significant work which isn't really warranted for a project I'm no longer developing. The only reason to do it would be to have one more test project to debug Godot on.

**Comment by rzejek** [comment]
Ok, thanks to let me know. The project works with Godot version 3.6 on my linux machine.
