### ISSUE TITLE
Crash when you make two players put a bomb in the same direction and in the same position

### ISSUE THREAD

**Issue by erik90mx** [akien-mga/dynadungeons#8]
1-You need to put player one to player two position (down corner)

2-Use player two now, and press the right to point in that direction

3-Use player one now, walk until it is overlapping the player two, pointing at the same direction (right at the limit of the right wall and bottom wall)

4-Use TAB and ENTER at the same time

It will make something like this:
http://s1.postimg.org/tptxy6hpr/screenshot_62.png

5-The game crash 
http://s1.postimg.org/ga6x8q97z/screenshot_63.png

PD: This is the GODOT terminal at the time of the crash
http://s1.postimg.org/d4qww9fzj/screenshot_64.png

Using commit 45c8455

Greetings

**Comment by ObaniGemini** [comment]
@erik90mx : this glitch with players in walls work with all players : when two bombs are put in a corner with a player, the player will go in the wall.

**Comment by akien-mga** [comment]
The crash in itself should be fixed by f96c159.

For the fact that bombs can move players in the walls, etc., I'll investigate :)

**Comment by akien-mga** [comment]
Thanks for the detailed procedure @erik90mx, you are great at doing QA :)
I fixed this bug by simply making sure that all players that are on its tile when the bomb is placed are exempt from collision with this bomb, and not only the player who drops the bomb as previously.
